var searchData=
[
  ['pad',['Pad',['../classfastdeploy_1_1vision_1_1Pad.html',1,'fastdeploy::vision']]],
  ['paddlebackendoption',['PaddleBackendOption',['../structfastdeploy_1_1PaddleBackendOption.html',1,'fastdeploy']]],
  ['paddleclasmodel',['PaddleClasModel',['../classfastdeploy_1_1vision_1_1classification_1_1PaddleClasModel.html',1,'fastdeploy::vision::classification']]],
  ['paddleclaspostprocessor',['PaddleClasPostprocessor',['../classfastdeploy_1_1vision_1_1classification_1_1PaddleClasPostprocessor.html',1,'fastdeploy::vision::classification']]],
  ['paddleclaspreprocessor',['PaddleClasPreprocessor',['../classfastdeploy_1_1vision_1_1classification_1_1PaddleClasPreprocessor.html',1,'fastdeploy::vision::classification']]],
  ['paddledetpostprocessor',['PaddleDetPostprocessor',['../classfastdeploy_1_1vision_1_1detection_1_1PaddleDetPostprocessor.html',1,'fastdeploy::vision::detection']]],
  ['paddledetpreprocessor',['PaddleDetPreprocessor',['../classfastdeploy_1_1vision_1_1detection_1_1PaddleDetPreprocessor.html',1,'fastdeploy::vision::detection']]],
  ['paddlesegmodel',['PaddleSegModel',['../classfastdeploy_1_1vision_1_1segmentation_1_1PaddleSegModel.html',1,'fastdeploy::vision::segmentation']]],
  ['paddlesegpostprocessor',['PaddleSegPostprocessor',['../classfastdeploy_1_1vision_1_1segmentation_1_1PaddleSegPostprocessor.html',1,'fastdeploy::vision::segmentation']]],
  ['paddlesegpreprocessor',['PaddleSegPreprocessor',['../classfastdeploy_1_1vision_1_1segmentation_1_1PaddleSegPreprocessor.html',1,'fastdeploy::vision::segmentation']]],
  ['padtosize',['PadToSize',['../classfastdeploy_1_1vision_1_1PadToSize.html',1,'fastdeploy::vision']]],
  ['pfld',['PFLD',['../classfastdeploy_1_1vision_1_1facealign_1_1PFLD.html',1,'fastdeploy::vision::facealign']]],
  ['pipnet',['PIPNet',['../classfastdeploy_1_1vision_1_1facealign_1_1PIPNet.html',1,'fastdeploy::vision::facealign']]],
  ['porosbackendoption',['PorosBackendOption',['../structfastdeploy_1_1PorosBackendOption.html',1,'fastdeploy']]],
  ['ppdetbase',['PPDetBase',['../classfastdeploy_1_1vision_1_1detection_1_1PPDetBase.html',1,'fastdeploy::vision::detection']]],
  ['ppmatting',['PPMatting',['../classfastdeploy_1_1vision_1_1matting_1_1PPMatting.html',1,'fastdeploy::vision::matting']]],
  ['ppocrv2',['PPOCRv2',['../classfastdeploy_1_1pipeline_1_1PPOCRv2.html',1,'fastdeploy::pipeline']]],
  ['ppocrv3',['PPOCRv3',['../classfastdeploy_1_1pipeline_1_1PPOCRv3.html',1,'fastdeploy::pipeline']]],
  ['pptinypose',['PPTinyPose',['../classfastdeploy_1_1vision_1_1keypointdetection_1_1PPTinyPose.html',1,'fastdeploy::vision::keypointdetection::PPTinyPose'],['../classfastdeploy_1_1pipeline_1_1PPTinyPose.html',1,'fastdeploy::pipeline::PPTinyPose']]],
  ['processor',['Processor',['../classfastdeploy_1_1vision_1_1Processor.html',1,'fastdeploy::vision']]],
  ['processormanager',['ProcessorManager',['../classfastdeploy_1_1vision_1_1ProcessorManager.html',1,'fastdeploy::vision']]]
];
